import { Prompt, Category } from './types';

export const MOCK_CATEGORIES: Category[] = [
  { id: '1', name: 'Art & Design',  slug: 'art',      icon: '🎨', color: '#f97316' },
  { id: '2', name: 'Coding',        slug: 'coding',   icon: '💻', color: '#3b82f6' },
  { id: '3', name: 'Writing',       slug: 'writing',  icon: '✍️', color: '#8b5cf6' },
  { id: '4', name: 'Marketing',     slug: 'marketing',icon: '📣', color: '#10b981' },
  { id: '5', name: 'Photography',   slug: 'photo',    icon: '📸', color: '#ec4899' },
  { id: '6', name: 'Video',         slug: 'video',    icon: '🎬', color: '#0ea5e9' },
  { id: '7', name: 'Music',         slug: 'music',    icon: '🎵', color: '#f59e0b' },
  { id: '8', name: 'Business',      slug: 'business', icon: '💼', color: '#6366f1' },
];

export const MOCK_PROMPTS: Prompt[] = [
  {
    id: '1', title: 'Cyberpunk City Nightscape',
    text: 'A sprawling cyberpunk metropolis at midnight, neon signs reflecting on rain-soaked streets, holographic advertisements floating in the misty air, silhouettes of flying vehicles weaving between towering skyscrapers, ultra-detailed, cinematic lighting, 8K resolution, by Syd Mead and Blade Runner aesthetic',
    category: 'art', platform: 'midjourney',
    tags: ['cyberpunk', 'city', 'neon', 'sci-fi', 'night'],
    image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=800&q=80',
    likes: 1284, copies: 3421, is_featured: true, created_at: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '2', title: 'Python FastAPI Expert',
    text: 'You are a senior Python engineer specializing in FastAPI. Help me design a RESTful API with JWT authentication, rate limiting, async database operations using SQLAlchemy, proper error handling with custom exception classes, and OpenAPI documentation. Follow clean architecture principles and SOLID design patterns.',
    category: 'coding', platform: 'chatgpt',
    tags: ['python', 'fastapi', 'backend', 'api', 'jwt'],
    image_url: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=800&q=80',
    likes: 892, copies: 2100, is_featured: true, created_at: new Date(Date.now() - 172800000).toISOString(),
  },
  {
    id: '3', title: 'Enchanted Forest Portrait',
    text: 'A ethereal portrait of a forest spirit, long flowing silver hair entwined with glowing fireflies, wearing an elaborate gown made of autumn leaves, ancient moss-covered trees in background, magical golden hour light filtering through canopy, photorealistic, Canon EOS R5 look, depth of field, dreamlike atmosphere',
    category: 'photo', platform: 'dalle',
    tags: ['portrait', 'fantasy', 'forest', 'magical', 'ethereal'],
    image_url: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80',
    likes: 2156, copies: 4890, is_featured: true, created_at: new Date(Date.now() - 259200000).toISOString(),
  },
  {
    id: '4', title: 'Viral Product Launch Email',
    text: 'Write a compelling product launch email sequence (3 emails) for a SaaS tool targeting solopreneurs. Email 1: Tease the problem. Email 2: Reveal the solution with social proof. Email 3: Urgency-driven offer with CTA. Use conversational tone, short paragraphs, bullet points for features, and power words.',
    category: 'marketing', platform: 'gemini',
    tags: ['email', 'saas', 'marketing', 'copywriting', 'launch'],
    image_url: 'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800&q=80',
    likes: 743, copies: 1890, is_featured: false, created_at: new Date(Date.now() - 345600000).toISOString(),
  },
  {
    id: '5', title: 'Brutalist Architecture Interior',
    text: 'Interior of a brutalist concrete building transformed into a luxury living space, raw concrete walls with embedded LED strips, minimalist Scandinavian furniture, floor-to-ceiling windows overlooking a misty mountain range, dramatic shadows, high contrast black and white accent pieces, architectural photography style, wide angle 16mm',
    category: 'art', platform: 'stable-diffusion',
    tags: ['brutalist', 'interior', 'architecture', 'luxury', 'concrete'],
    image_url: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80',
    likes: 567, copies: 1234, is_featured: false, created_at: new Date(Date.now() - 432000000).toISOString(),
  },
  {
    id: '6', title: 'Sci-Fi Novel Chapter Writer',
    text: "You are Arthur C. Clarke collaborating with Isaac Asimov. Write a gripping opening chapter for a hard sci-fi novel set in 2157. The story begins with humanity discovering an alien signal originating from inside the Sun. Include scientific accuracy, complex morally-grey characters, philosophical undertones, and end with a cliffhanger.",
    category: 'writing', platform: 'claude',
    tags: ['sci-fi', 'novel', 'writing', 'space', 'creative'],
    image_url: 'https://images.unsplash.com/photo-1462332420958-a05d1e002413?w=800&q=80',
    likes: 1456, copies: 2800, is_featured: true, created_at: new Date(Date.now() - 518400000).toISOString(),
  },
  {
    id: '7', title: 'Cinematic Ocean Drone Shot',
    text: 'Generate a cinematic aerial drone shot over a tropical ocean at sunrise, turquoise water with visible coral reefs below the surface, a lone wooden sailing boat casting a long shadow, golden rays piercing through thin clouds, timelapse motion blur on waves, 4K drone footage aesthetic, color graded like a Netflix nature documentary',
    category: 'video', platform: 'sora',
    tags: ['drone', 'ocean', 'cinematic', 'sunrise', 'nature'],
    image_url: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800&q=80',
    likes: 3201, copies: 5600, is_featured: true, created_at: new Date(Date.now() - 604800000).toISOString(),
  },
  {
    id: '8', title: 'Lo-Fi Music Generator',
    text: 'Compose a lo-fi hip hop track description: BPM 75-85, Key C minor, dusty vinyl-sampled piano, muffled jazz drums, warm bass, vinyl crackle. Mood: nostalgic study session at 2am. Include Ableton production notes, sample recommendations, chord progressions. Reference: Nujabes, J Dilla, Idealism.',
    category: 'music', platform: 'gemini',
    tags: ['lofi', 'music', 'hip-hop', 'production', 'chill'],
    image_url: 'https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=800&q=80',
    likes: 891, copies: 1567, is_featured: false, created_at: new Date(Date.now() - 691200000).toISOString(),
  },
  {
    id: '9', title: 'VC Pitch Deck Analyzer',
    text: "Act as a seasoned venture capitalist who has reviewed 10,000+ pitch decks. Analyze my startup pitch deck slide by slide. For each slide identify: what's working, what's missing, red flags investors will notice, and specific improvements with examples from Airbnb, Uber, Dropbox decks. End with an overall fundability score (1-10).",
    category: 'business', platform: 'chatgpt',
    tags: ['startup', 'pitchdeck', 'vc', 'fundraising', 'business'],
    image_url: 'https://images.unsplash.com/photo-1559136555-9303baea8ebd?w=800&q=80',
    likes: 2341, copies: 4200, is_featured: true, created_at: new Date(Date.now() - 777600000).toISOString(),
  },
  {
    id: '10', title: 'Watercolor Galaxy Portrait',
    text: "A beautiful watercolor painting of a person's silhouette filled with a swirling galaxy, nebula colors of deep purple, electric blue and rose gold, stars scattered like freckles, delicate ink outlines, loose brushstrokes, white paper texture showing through, in the style of Leonid Afremov meets cosmic art",
    category: 'art', platform: 'midjourney',
    tags: ['watercolor', 'galaxy', 'portrait', 'space', 'painting'],
    image_url: 'https://images.unsplash.com/photo-1534796636912-3b95b3ab5986?w=800&q=80',
    likes: 4521, copies: 7800, is_featured: true, created_at: new Date(Date.now() - 864000000).toISOString(),
  },
  {
    id: '11', title: 'React Architecture Advisor',
    text: 'You are a principal frontend engineer at a FAANG company. Review my React application architecture and suggest improvements for: state management (Zustand vs Context vs Redux), component composition patterns, performance optimization, testing strategy, folder structure for a team of 20+ engineers, and TypeScript strict mode patterns.',
    category: 'coding', platform: 'claude',
    tags: ['react', 'typescript', 'architecture', 'frontend', 'performance'],
    image_url: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=800&q=80',
    likes: 1678, copies: 3900, is_featured: false, created_at: new Date(Date.now() - 950400000).toISOString(),
  },
  {
    id: '12', title: 'Bioluminescent Deep Sea',
    text: 'Photograph-realistic image of a deep sea scene, 2000 meters below ocean surface, bioluminescent creatures glowing in electric blue and green, massive anglerfish with glowing lure, transparent jellyfish with visible internal organs, volcanic hydrothermal vents, absolute darkness punctuated by organic light, National Geographic quality',
    category: 'photo', platform: 'dalle',
    tags: ['ocean', 'bioluminescent', 'deep-sea', 'nature', 'photography'],
    image_url: 'https://images.unsplash.com/photo-1518020382113-a7e8fc38eac9?w=800&q=80',
    likes: 3892, copies: 6700, is_featured: true, created_at: new Date(Date.now() - 1036800000).toISOString(),
  },
];
